version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mywebsite:latest
    container_name: site-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: site-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "4431:443"
    volumes:
      - ./:/var/www
      - ./docker-conf/nginx/conf.d/:/etc/nginx/conf.d/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/ssl/:/etc/ssl/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
